ALTER TABLE ParkingSpot DROP FOREIGN KEY FKParkingSpo163974;
ALTER TABLE Reservation DROP FOREIGN KEY FKReservatio589727;
DROP TABLE IF EXISTS ParkingLot;
DROP TABLE IF EXISTS ParkingSpot;
DROP TABLE IF EXISTS Reservation;

